spring:
  application:
    name: demo
  config:
    import: optional:aws-secretsmanager:/secret/demo

sample:
  id: ${id:test}
  password: ${password:test}

custom:
  token: ${token_value:U2FtcGxlIERldk9wcyB0b2tlbiB2YWx1ZXMK}